

services:
  # --- BASE DE DONNÉES ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    # On charge les variables (POSTGRES_USER, POSTGRES_PASSWORD) depuis le .env du backend
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- GESTIONNAIRE DE BASE DE DONNÉES ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_panel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # --- BACKEND (FastAPI) ---
  backend:
    build: ./backend
    container_name: fastapi_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    # Charge DATABASE_URL, SECRET_KEY, etc.
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # --- FRONTEND (React + Vite) ---
  frontend:
    build:
      context: ./frontend
      args:
        # Docker va chercher cette valeur dans ton .env à la racine ou celui du frontend
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    container_name: react_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

# Définition du volume nommé pour que les données survivent au redémarrage
volumes:
  postgres_data: