"""ajout_hierarchie_education_et_status

Revision ID: 319b72754dc0
Revises: 673033e20e11
Create Date: 2026-03-12 23:57:21.109676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319b72754dc0'
down_revision: Union[str, Sequence[str], None] = '673033e20e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cycles_id'), 'cycles', ['id'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filieres_id'), 'filieres', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.add_column('subjects', sa.Column('filiere_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('subjects_name_key'), 'subjects', type_='unique')
    op.create_foreign_key(None, 'subjects', 'filieres', ['filiere_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'enrollment_status',
               existing_type=postgresql.ENUM('PENDING_PROFILE', 'PENDING_PAYMENT', 'ACTIVE', name='enrollmentstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING_PROFILE'::enrollmentstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'enrollment_status',
               existing_type=postgresql.ENUM('PENDING_PROFILE', 'PENDING_PAYMENT', 'ACTIVE', name='enrollmentstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING_PROFILE'::enrollmentstatus"))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_unique_constraint(op.f('subjects_name_key'), 'subjects', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('subjects', 'filiere_id')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_filieres_id'), table_name='filieres')
    op.drop_table('filieres')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_cycles_id'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
