"""add topic to quiz

Revision ID: 3d7b7c5692b5
Revises: fdbc537630fb
Create Date: 2026-03-10 23:36:54.706911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7b7c5692b5'
down_revision: Union[str, Sequence[str], None] = 'fdbc537630fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'topic')
    # ### end Alembic commands ###
