"""fix_user_relationships

Revision ID: e07956cc7425
Revises: 319b72754dc0
Create Date: 2026-03-13 00:14:26.668998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07956cc7425'
down_revision: Union[str, Sequence[str], None] = '319b72754dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('filiere_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'users', 'filieres', ['filiere_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'filiere_id')
    op.drop_column('users', 'level_id')
    # ### end Alembic commands ###
